#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3
bspc monitor HDMI-0 -d I II III

$HOME/.config/polybar/launch.sh 
$HOME/autostart.sh

bspc config border_width         2
bspc config window_gap           4
bspc config right_padding        2
bspc config left_padding         2

bspc config normal_border_color  "#252525"
bspc config focused_border_color "#b48ead"

bspc config split_ratio          0.52

bspc config focus_follows_pointer true

bspc -rule -a feh state=floating
bspc -rule -a pcmanfm state=floating
bspc -rule -a vlc state=floating
